# Generated by Django 4.0.2 on 2022-02-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(default='file', max_length=30),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_date',
            field=models.CharField(default='date', max_length=30),
        ),
    ]
