# Generated by Django 3.2.5 on 2022-02-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_uploadedfile_file_type_uploadedfile_uploaded_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='user_profile.png', upload_to='')),
                ('username', models.CharField(max_length=30)),
                ('eMail', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('security_question', models.CharField(max_length=100)),
                ('security_answer', models.CharField(max_length=100)),
                ('admin', models.BooleanField(default=False)),
                ('user_id', models.IntegerField(default='0')),
            ],
        ),
    ]
