# Generated by Django 4.0.1 on 2022-02-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profiles_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('file_name', models.CharField(max_length=30)),
                ('file_type', models.CharField(default='file', max_length=30)),
                ('uploader', models.CharField(max_length=30)),
                ('uploaded_date', models.CharField(default='date', max_length=30)),
            ],
        ),
    ]
