# Generated by Django 3.2.5 on 2022-02-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20220216_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
